# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20151222_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='extras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='discos',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fabricante',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='gabinete',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='lectora',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='memorias',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='placa_de_video',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='placa_madre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='procesador',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
